---

- name: Print vpg_identifiers fact
  debug:
    msg: "vpg_identifiers :: {{ vpg_identifiers }}"
    
- name: perform zerto vpg failovertest
  zerto_vpg_failovertest:
    zvm_ipaddress: "{{ zerto['infra']['zvm_ipaddress'] }}"
    vpg_vpgidentifier: "{{ item }}"
    session_key: "{{ session_key }}"
  register: zerto_vpg_failovertest_output
  loop: "{{ vpg_identifiers }}"
  ignore_errors: yes

- name: Print if zerto vpg failover  API failed
  fail:
    msg: "Failed while perform the failover for VPG: {{ zerto['infra']['zvm_vpg_name'][index] }}"
  when: zerto_vpg_failovertest_output.results[index].failed == true
  loop: "{{ zerto['infra']['zvm_vpg_name'] }}"
  loop_control:
    index_var: index

- name: Print if zerto vpg failover  API success
  debug:
    msg: "{{ zerto_vpg_failovertest_output.results[index].task_id }} for {{ zerto['infra']['zvm_vpg_name'][index] }}"
  when: zerto_vpg_failovertest_output.results[index].failed == false
  loop: "{{ zerto['infra']['zvm_vpg_name'] }}"
  loop_control:
    index_var: index
